#!/bin/bash

files=(
    "CInstanceManager.js"
    "CGlobalConstManager.js"
    "CNameKana.js"
    "CCustomSelectBase.js"
    "CCustomSelectMapBase.js"
    "CCustomSelectMapCategory.js"
    "CCustomSelectMapMap.js"
    "CCustomSelectMapMonster.js"
    "common.js"
    "etc.js"
    "alias.h.js"
    "alias.dat.js"
    "chara.dat.js"
    "skill.h.js"
    "skill.dat.js"
    "usableskill.h.js"
    "usableskill.dat.js"
    "autospell.h.js"
    "autospell.dat.js"
    "CSkillManager.js"
    "monster.h.js"
    "monster.dat.js"
    "monstergroup.dat.js"
    "monstermap.h.js"
    "monstermap.dat.js"
    "item.h.js"
    "item.dat.js"
    "arrow.h.js"
    "arrow.dat.js"
    "card.h.js"
    "card.dat.js"
    "costume.h.js"
    "costume.dat.js"
    "pet.h.js"
    "pet.dat.js"
    "itemset.h.js"
    "itemset.dat.js"
    "rndopt.h.js"
    "rndopt.dat.js"
    "rndoptlist.h.js"
    "rndoptlist.dat.js"
    "rndopttype.h.js"
    "rndopttype.dat.js"
    "timeitem.h.js"
    "timeitem.dat.js"
    "itempack.h.js"
    "itempack.dat.js"

    "data/mig.itemsp.h.js"
    "data/CMigJobData.js"
    "data/CMigStateData.js"
    "data/CMigEquipableSpTag.js"
    "data/CMigEquipableStaticData.js"
    "data/CMigEquipableSpData.js"
    "data/CMigEquipableData.js"
    "data/CMigConstDataManagerSubBase.js"
    "data/CMigConstDataManagerSubJob.js"
    "data/CMigConstDataManagerSubState.js"
    "data/CMigConstDataManagerSubBuff.js"
    "data/CMigConstDataManagerSubMonster.js"
    "data/CMigConstDataManagerSubArrow.js"
    "data/CMigConstDataManagerSubItem.js"
    "data/CMigConstDataManagerSubCard.js"
    "data/CMigConstDataManagerSubEnchList.js"
    "data/CMigConstDataManagerSubRndOpt.js"
    "data/CMigConstDataManager.js"

    "data/mig.enchlist.dat.js"

    "rndench.js"
    "equip.js"
    "learnedskill.js"
    "slotpager.js"
    "spmode.js"
    "quickcontrol.js"

    "chara.js"
    "mob.js"
    "CAttackMethodConf.js"

    "CConfBase.js"
    "CConfBase2.js"
    "CCharaConfIchizi.js"
    "CCharaConfNizi.js"
    "CCharaConfSanzi.js"
    "CCharaConfYozi.js"
    "CCharaConfCustomStatus.js"
    "CCharaConfCustomAtk.js"
    "CCharaConfCustomDef.js"
    "CCharaConfCustomSkill.js"

    "mobconfdebuf.js"
    "mobconfbuf.js"
    "mobconfplayer.js"
    "CMobConfInput.js"

    "CItemInfoManager.js"
    "hmcard.js"
    "hmcostume.js"
    "hmrndopt.js"
    "hmchara.js"
    "hmmob.js"

    "castsim.js"
    
    "CTimeItemAreaComponentManager.js"
    "CBattleQuickControlAreaComponentManager.js"
    "CExtraInfoAreaComponentManager.js"
    "CFloatingInfoAreaComponentManager.js"
    "CCalcDataTextCreator.js"

    "CSaveDataMappingManager.js"
    "CSaveDataConverter.js"
    "saveload.js"

    "foot.js"
)

for str in ${files[@]}; do
  echo $str
  curl -sS https://roratorio-hinanjo.net/roro/m/js/$str > public/assets/js/$str
done
